데이터셋: http://www.manythings.org/anki fra-eng


In [1]:
import sys
import pathlib
import os

sys.path.append(str(pathlib.Path(os.getcwd()).parent))

import copy
import re
import unicodedata
import numpy as np
import pandas as pd
import torch
from collections import Counter
from tqdm import tqdm
from torch.utils.data import TensorDataset, DataLoader

from src.base_module import *
from src.transformer import Transformer

In [2]:
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f'device: {device}')

device: mps


In [3]:
num_samples = 33000

In [4]:
def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

def preprocess_sentence(sent):
    sent = unicode_to_ascii(sent.lower())
    sent = re.sub(r"([?.!,¿])", r" \1", sent)
    sent = re.sub(r"[^a-zA-Z!.?]+", r" ", sent)
    sent = re.sub(r"\s+", " ", sent)

    return sent

def load_preprocess_data():
    encoder_input, decoder_input, decoder_target = [], [], []

    with open('./fra.txt', 'r') as f:
        lines = f.readlines()[:num_samples]
        for i, line in enumerate(lines):
            src, tar, _ = line.strip().split('\t')
            src = [w for w in preprocess_sentence(src).split()]
            tar = preprocess_sentence(tar)
            tgt_in = [w for w in f'<sos> {tar}'.split()]
            tgt_out = [w for w in f'{tar} <eos>'.split()]

            encoder_input.append(src)
            decoder_input.append(tgt_in)
            decoder_target.append(tgt_out)

    return encoder_input, decoder_input, decoder_target

In [5]:
en_sent = u"Have you had dinner?"
fr_sent = u"Avez-vous déjà diné?"

print(f'{en_sent} -> {preprocess_sentence(en_sent)}')
print(f'{fr_sent} -> {preprocess_sentence(fr_sent)}')

Have you had dinner? -> have you had dinner ?
Avez-vous déjà diné? -> avez vous deja dine ?


In [6]:
sents_en_in, sents_fra_in, sents_fra_out = load_preprocess_data()

print(len(sents_en_in))
print(len(sents_fra_in))
print(len(sents_fra_out))

33000
33000
33000


In [7]:
print(sents_en_in[:5])
print(sents_fra_in[:5])
print(sents_fra_out[:5])

[['go', '.'], ['go', '.'], ['go', '.'], ['go', '.'], ['hi', '.']]
[['<sos>', 'va', '!'], ['<sos>', 'marche', '.'], ['<sos>', 'en', 'route', '!'], ['<sos>', 'bouge', '!'], ['<sos>', 'salut', '!']]
[['va', '!', '<eos>'], ['marche', '.', '<eos>'], ['en', 'route', '!', '<eos>'], ['bouge', '!', '<eos>'], ['salut', '!', '<eos>']]


In [8]:
def build_vocab(sents):
    words = []
    for sent in sents:
        for word in sent:
            words.append(word)

    word_counts = Counter(words)
    vocab = sorted(word_counts, key=word_counts.get, reverse=True)

    word2index = {}
    word2index['<PAD>'] = 0
    word2index['<UNK>'] = 1

    for i, word in enumerate(vocab):
        word2index[word] = i + 2

    return word2index

In [9]:
src_vocab = build_vocab(sents_en_in)
tgt_vocab = build_vocab(sents_fra_in + sents_fra_out)

src_vocab_size = len(src_vocab)
tgt_vocab_size = len(tgt_vocab)

print(f'src vocab size: {src_vocab_size}')
print(f'tar vocab size: {tgt_vocab_size}')

src vocab size: 4486
tar vocab size: 7879


In [10]:
index2src = {v: k for k, v in src_vocab.items()}
index2tar = {v: k for k, v in tgt_vocab.items()}

In [11]:
def encode_sentences(sents, word2index):
    encoded_data = []
    for sent in tqdm(sents):
        encoded_sent = []
        for word in sent:
            try:
                encoded_sent.append(word2index[word])
            except KeyError:
                encoded_sent.append(word2index['<UNK>'])
        encoded_data.append(encoded_sent)

    return encoded_data

In [12]:
encoder_input = encode_sentences(sents_en_in, src_vocab)
decoder_input = encode_sentences(sents_fra_in, tgt_vocab)
decoder_target = encode_sentences(sents_fra_out, tgt_vocab)

100%|██████████| 33000/33000 [00:00<00:00, 2252433.39it/s]


In [13]:
print(encoder_input[:5])
print(decoder_input[:5])
print(decoder_target[:5])

[[27, 2], [27, 2], [27, 2], [27, 2], [736, 2]]
[[3, 68, 11], [3, 204, 2], [3, 26, 491, 11], [3, 561, 11], [3, 954, 11]]
[[68, 11, 4], [204, 2, 4], [26, 491, 11, 4], [561, 11, 4], [954, 11, 4]]


In [14]:
def pad_sentences(sents, max_len=None):
    if max_len is None:
        max_len = max([len(s) for s in sents])

    features = np.zeros((len(sents), max_len), dtype=int)
    for i, sent in enumerate(sents):
        features[i, :len(sent)] = np.array(sent)[:max_len]

    return features

In [15]:
encoder_input = pad_sentences(encoder_input)
decoder_input = pad_sentences(decoder_input)
decoder_target = pad_sentences(decoder_target)

In [16]:
print(encoder_input[:3])
print(decoder_input[:3])
print(decoder_target[:3])

[[27  2  0  0  0  0  0]
 [27  2  0  0  0  0  0]
 [27  2  0  0  0  0  0]]
[[  3  68  11   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  3 204   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  3  26 491  11   0   0   0   0   0   0   0   0   0   0   0   0]]
[[ 68  11   4   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [204   2   4   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 26 491  11   4   0   0   0   0   0   0   0   0   0   0   0   0]]


In [17]:
print(encoder_input.shape)
print(decoder_input.shape)
print(decoder_target.shape)

(33000, 7)
(33000, 16)
(33000, 16)


In [18]:
indices = np.arange(encoder_input.shape[0])
np.random.shuffle(indices)
print('랜덤 시퀀스 :',indices)

랜덤 시퀀스 : [16524 13883  6925 ... 16031 13706 11227]


In [19]:
encoder_input = encoder_input[indices]
decoder_input = decoder_input[indices]
decoder_target = decoder_target[indices]

In [20]:
print([index2src[word] for word in encoder_input[30997]])
print([index2tar[word] for word in decoder_input[30997]])
print([index2tar[word] for word in decoder_target[30997]])

['i', 'can', 't', 'fix', 'this', '.', '<PAD>']
['<sos>', 'je', 'n', 'arrive', 'pas', 'a', 'reparer', 'ceci', '.', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>']
['je', 'n', 'arrive', 'pas', 'a', 'reparer', 'ceci', '.', '<eos>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>']


In [21]:
n_of_val = int(num_samples * 0.1)
print('검증 데이터의 개수 :',n_of_val)

encoder_input_train = encoder_input[:-n_of_val]
decoder_input_train = decoder_input[:-n_of_val]
decoder_target_train = decoder_target[:-n_of_val]

encoder_input_test = encoder_input[-n_of_val:]
decoder_input_test = decoder_input[-n_of_val:]
decoder_target_test = decoder_target[-n_of_val:]

검증 데이터의 개수 : 3300


In [22]:
print('훈련 source 데이터의 크기 :',encoder_input_train.shape)
print('훈련 target 데이터의 크기 :',decoder_input_train.shape)
print('훈련 target 레이블의 크기 :',decoder_target_train.shape)
print('테스트 source 데이터의 크기 :',encoder_input_test.shape)
print('테스트 target 데이터의 크기 :',decoder_input_test.shape)
print('테스트 target 레이블의 크기 :',decoder_target_test.shape)

훈련 source 데이터의 크기 : (29700, 7)
훈련 target 데이터의 크기 : (29700, 16)
훈련 target 레이블의 크기 : (29700, 16)
테스트 source 데이터의 크기 : (3300, 7)
테스트 target 데이터의 크기 : (3300, 16)
테스트 target 레이블의 크기 : (3300, 16)


In [23]:
encoder_input_train_tensor = torch.tensor(encoder_input_train, dtype=torch.long)
decoder_input_train_tensor = torch.tensor(decoder_input_train, dtype=torch.long)
decoder_target_train_tensor = torch.tensor(decoder_target_train, dtype=torch.long)

encoder_input_test_tensor = torch.tensor(encoder_input_test, dtype=torch.long)
decoder_input_test_tensor = torch.tensor(decoder_input_test, dtype=torch.long)
decoder_target_test_tensor = torch.tensor(decoder_target_test, dtype=torch.long)

# 데이터셋 및 데이터로더 생성
batch_size = 512

train_dataset = TensorDataset(encoder_input_train_tensor, decoder_input_train_tensor, decoder_target_train_tensor)
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

valid_dataset = TensorDataset(encoder_input_test_tensor, decoder_input_test_tensor, decoder_target_test_tensor)
valid_dataloader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)

In [24]:
max_len = 20
d_embed = 128
d_model = 128
n_layer = 4
h = 4
d_ff = 256

src_token_embed = TokenEmbedding(d_embed=d_embed, vocab_size=src_vocab_size)
tgt_token_embed = TokenEmbedding(d_embed=d_embed, vocab_size=tgt_vocab_size)
pos_embed = PositionalEncoding(d_embed=d_embed, max_len=max_len, device=device)
src_embed = TransformerEmbedding(token_embed=src_token_embed, pos_embed=copy.deepcopy(pos_embed))
tgt_embed = TransformerEmbedding(token_embed=tgt_token_embed, pos_embed=copy.deepcopy(pos_embed))

attention = MultiHeadAttentionLayer(d_model=d_model, h=h, qkv_fc=nn.Linear(d_embed, d_model), out_fc=nn.Linear(d_model, d_embed)).to(device)
position_ff = PositionWiseFeedForwardLayer(fc1=nn.Linear(d_embed, d_ff), fc2=nn.Linear(d_ff, d_embed)).to(device)

encoder_block = EncoderBlock(self_attention=copy.deepcopy(attention), position_ff=copy.deepcopy(position_ff), d_model=d_model, device=device)
decoder_block = DecoderBlock(self_attention=copy.deepcopy(attention), cross_attention=copy.deepcopy(attention), position_ff=copy.deepcopy(position_ff), d_model=d_model, device=device)

encoder = Encoder(encoder_block=encoder_block, n_layer=n_layer)
decoder = Decoder(decoder_block=decoder_block, n_layer=n_layer)

generator = nn.Linear(d_embed, tgt_vocab_size)

model = Transformer(
    src_embed=src_embed,
    tgt_embed=tgt_embed,
    encoder=encoder,
    decoder=decoder,
    generator=generator
).to(device)
loss_function = nn.CrossEntropyLoss(ignore_index=0).to(device)
optimizer = torch.optim.Adam(model.parameters())

In [25]:
def evaluation(model, dataloader, loss_function, device):
    model.eval()
    total_loss = 0.0
    total_correct = 0
    total_count = 0

    with torch.no_grad():
        for encoder_inputs, decoder_inputs, decoder_targets in dataloader:
            encoder_inputs = encoder_inputs.to(device)
            decoder_inputs = decoder_inputs.to(device)
            decoder_targets = decoder_targets.to(device)

            outputs, _ = model(encoder_inputs, decoder_inputs)

            loss = loss_function(outputs.view(-1, outputs.size(-1)), decoder_targets.view(-1))
            total_loss += loss.item()

            mask = decoder_targets != 0
            total_correct += ((outputs.argmax(dim=-1) == decoder_targets) * mask).sum().item()
            total_count += mask.sum().item()

    return total_loss / len(dataloader), total_correct / total_count

In [26]:
num_epochs = 40

In [27]:
for encoder_inputs, decoder_inputs, decoder_targets in tqdm(train_dataloader):
    encoder_inputs = encoder_inputs.to(device)
    decoder_inputs = decoder_inputs.to(device)
    decoder_targets = decoder_targets.to(device)
    print(decoder_inputs[0])
    print(decoder_targets[0])
    break

  0%|          | 0/59 [00:00<?, ?it/s]

tensor([  3,   8,   6, 400, 531,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0], device='mps:0')
tensor([  8,   6, 400, 531,   2,   4,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0], device='mps:0')


In [28]:
best_val_loss = float('inf')

for epoch in range(num_epochs):
    model.train()

    for encoder_inputs, decoder_inputs, decoder_targets in tqdm(train_dataloader):
        encoder_inputs = encoder_inputs.to(device)
        decoder_inputs = decoder_inputs.to(device)
        decoder_targets = decoder_targets.to(device)
        optimizer.zero_grad()

        outputs, _ = model(encoder_inputs, decoder_inputs)

        loss = loss_function(outputs.view(-1, outputs.size(-1)), decoder_targets.view(-1))
        loss.backward()
        optimizer.step()

    train_loss, train_acc = evaluation(model, train_dataloader, loss_function, device)
    valid_loss, valid_acc = evaluation(model, valid_dataloader, loss_function, device)

    print(f'Epoch: {epoch+1}/{num_epochs} | Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | Valid Loss: {valid_loss:.4f} | Valid Acc: {valid_acc:.4f}')

    if valid_loss < best_val_loss:
        print(f'Validation loss improved from {best_val_loss:.4f} to {valid_loss:.4f}. 체크포인트를 저장합니다.')
        best_val_loss = valid_loss
        torch.save(model.state_dict(), 'best_model_checkpoint.pth')


100%|██████████| 59/59 [00:08<00:00,  7.27it/s]


Epoch: 1/40 | Train Loss: 5.2724 | Train Acc: 0.4410 | Valid Loss: 5.8602 | Valid Acc: 0.4267
Validation loss improved from inf to 5.8602. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.24it/s]


Epoch: 2/40 | Train Loss: 3.4791 | Train Acc: 0.5147 | Valid Loss: 4.1664 | Valid Acc: 0.4946
Validation loss improved from 5.8602 to 4.1664. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.56it/s]


Epoch: 3/40 | Train Loss: 2.7174 | Train Acc: 0.5526 | Valid Loss: 3.4928 | Valid Acc: 0.5282
Validation loss improved from 4.1664 to 3.4928. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.06it/s]


Epoch: 4/40 | Train Loss: 2.3150 | Train Acc: 0.5780 | Valid Loss: 3.1393 | Valid Acc: 0.5467
Validation loss improved from 3.4928 to 3.1393. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.46it/s]


Epoch: 5/40 | Train Loss: 2.0305 | Train Acc: 0.6064 | Valid Loss: 2.9188 | Valid Acc: 0.5658
Validation loss improved from 3.1393 to 2.9188. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.11it/s]


Epoch: 6/40 | Train Loss: 1.7921 | Train Acc: 0.6295 | Valid Loss: 2.7552 | Valid Acc: 0.5809
Validation loss improved from 2.9188 to 2.7552. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.32it/s]


Epoch: 7/40 | Train Loss: 1.6317 | Train Acc: 0.6489 | Valid Loss: 2.6365 | Valid Acc: 0.5942
Validation loss improved from 2.7552 to 2.6365. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.46it/s]


Epoch: 8/40 | Train Loss: 1.4825 | Train Acc: 0.6684 | Valid Loss: 2.5388 | Valid Acc: 0.6043
Validation loss improved from 2.6365 to 2.5388. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.40it/s]


Epoch: 9/40 | Train Loss: 1.3462 | Train Acc: 0.6878 | Valid Loss: 2.4629 | Valid Acc: 0.6146
Validation loss improved from 2.5388 to 2.4629. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.24it/s]


Epoch: 10/40 | Train Loss: 1.2280 | Train Acc: 0.7021 | Valid Loss: 2.4185 | Valid Acc: 0.6183
Validation loss improved from 2.4629 to 2.4185. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.57it/s]


Epoch: 11/40 | Train Loss: 1.1485 | Train Acc: 0.7172 | Valid Loss: 2.3628 | Valid Acc: 0.6269
Validation loss improved from 2.4185 to 2.3628. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.58it/s]


Epoch: 12/40 | Train Loss: 1.0602 | Train Acc: 0.7301 | Valid Loss: 2.3103 | Valid Acc: 0.6328
Validation loss improved from 2.3628 to 2.3103. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.55it/s]


Epoch: 13/40 | Train Loss: 0.9944 | Train Acc: 0.7456 | Valid Loss: 2.2896 | Valid Acc: 0.6391
Validation loss improved from 2.3103 to 2.2896. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.58it/s]


Epoch: 14/40 | Train Loss: 0.9371 | Train Acc: 0.7523 | Valid Loss: 2.2636 | Valid Acc: 0.6467
Validation loss improved from 2.2896 to 2.2636. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.58it/s]


Epoch: 15/40 | Train Loss: 0.8999 | Train Acc: 0.7594 | Valid Loss: 2.2625 | Valid Acc: 0.6489
Validation loss improved from 2.2636 to 2.2625. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.54it/s]


Epoch: 16/40 | Train Loss: 0.8583 | Train Acc: 0.7680 | Valid Loss: 2.2252 | Valid Acc: 0.6496
Validation loss improved from 2.2625 to 2.2252. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.27it/s]


Epoch: 17/40 | Train Loss: 0.8360 | Train Acc: 0.7712 | Valid Loss: 2.2293 | Valid Acc: 0.6523


100%|██████████| 59/59 [00:07<00:00,  8.30it/s]


Epoch: 18/40 | Train Loss: 0.7927 | Train Acc: 0.7799 | Valid Loss: 2.1880 | Valid Acc: 0.6606
Validation loss improved from 2.2252 to 2.1880. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.45it/s]


Epoch: 19/40 | Train Loss: 0.7697 | Train Acc: 0.7849 | Valid Loss: 2.2024 | Valid Acc: 0.6615


100%|██████████| 59/59 [00:07<00:00,  8.40it/s]


Epoch: 20/40 | Train Loss: 0.7490 | Train Acc: 0.7843 | Valid Loss: 2.1989 | Valid Acc: 0.6612


100%|██████████| 59/59 [00:07<00:00,  8.23it/s]


Epoch: 21/40 | Train Loss: 0.7261 | Train Acc: 0.7934 | Valid Loss: 2.1653 | Valid Acc: 0.6649
Validation loss improved from 2.1880 to 2.1653. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.23it/s]


Epoch: 22/40 | Train Loss: 0.6943 | Train Acc: 0.8011 | Valid Loss: 2.1633 | Valid Acc: 0.6704
Validation loss improved from 2.1653 to 2.1633. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.39it/s]


Epoch: 23/40 | Train Loss: 0.6844 | Train Acc: 0.8036 | Valid Loss: 2.1588 | Valid Acc: 0.6718
Validation loss improved from 2.1633 to 2.1588. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.34it/s]


Epoch: 24/40 | Train Loss: 0.6639 | Train Acc: 0.8067 | Valid Loss: 2.1574 | Valid Acc: 0.6698
Validation loss improved from 2.1588 to 2.1574. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:06<00:00,  8.51it/s]


Epoch: 25/40 | Train Loss: 0.6478 | Train Acc: 0.8090 | Valid Loss: 2.1456 | Valid Acc: 0.6777
Validation loss improved from 2.1574 to 2.1456. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.01it/s]


Epoch: 26/40 | Train Loss: 0.6228 | Train Acc: 0.8136 | Valid Loss: 2.1480 | Valid Acc: 0.6723


100%|██████████| 59/59 [00:07<00:00,  8.38it/s]


Epoch: 27/40 | Train Loss: 0.6174 | Train Acc: 0.8161 | Valid Loss: 2.1334 | Valid Acc: 0.6770
Validation loss improved from 2.1456 to 2.1334. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.39it/s]


Epoch: 28/40 | Train Loss: 0.6075 | Train Acc: 0.8169 | Valid Loss: 2.1382 | Valid Acc: 0.6754


100%|██████████| 59/59 [00:07<00:00,  8.14it/s]


Epoch: 29/40 | Train Loss: 0.5954 | Train Acc: 0.8222 | Valid Loss: 2.1527 | Valid Acc: 0.6789


100%|██████████| 59/59 [00:07<00:00,  8.38it/s]


Epoch: 30/40 | Train Loss: 0.6023 | Train Acc: 0.8185 | Valid Loss: 2.1750 | Valid Acc: 0.6740


100%|██████████| 59/59 [00:06<00:00,  8.54it/s]


Epoch: 31/40 | Train Loss: 0.6022 | Train Acc: 0.8210 | Valid Loss: 2.1620 | Valid Acc: 0.6781


100%|██████████| 59/59 [00:07<00:00,  8.09it/s]


Epoch: 32/40 | Train Loss: 0.5716 | Train Acc: 0.8275 | Valid Loss: 2.1427 | Valid Acc: 0.6816


100%|██████████| 59/59 [00:07<00:00,  8.31it/s]


Epoch: 33/40 | Train Loss: 0.5671 | Train Acc: 0.8260 | Valid Loss: 2.1740 | Valid Acc: 0.6826


100%|██████████| 59/59 [00:07<00:00,  8.23it/s]


Epoch: 34/40 | Train Loss: 0.5654 | Train Acc: 0.8294 | Valid Loss: 2.1371 | Valid Acc: 0.6824


100%|██████████| 59/59 [00:07<00:00,  8.27it/s]


Epoch: 35/40 | Train Loss: 0.5469 | Train Acc: 0.8310 | Valid Loss: 2.1385 | Valid Acc: 0.6840


100%|██████████| 59/59 [00:06<00:00,  8.45it/s]


Epoch: 36/40 | Train Loss: 0.5309 | Train Acc: 0.8360 | Valid Loss: 2.1240 | Valid Acc: 0.6869
Validation loss improved from 2.1334 to 2.1240. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.40it/s]


Epoch: 37/40 | Train Loss: 0.5191 | Train Acc: 0.8378 | Valid Loss: 2.1389 | Valid Acc: 0.6890


100%|██████████| 59/59 [00:07<00:00,  8.39it/s]


Epoch: 38/40 | Train Loss: 0.5041 | Train Acc: 0.8410 | Valid Loss: 2.1216 | Valid Acc: 0.6912
Validation loss improved from 2.1240 to 2.1216. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.23it/s]


Epoch: 39/40 | Train Loss: 0.4921 | Train Acc: 0.8456 | Valid Loss: 2.1129 | Valid Acc: 0.6920
Validation loss improved from 2.1216 to 2.1129. 체크포인트를 저장합니다.


100%|██████████| 59/59 [00:07<00:00,  8.31it/s]


Epoch: 40/40 | Train Loss: 0.4846 | Train Acc: 0.8484 | Valid Loss: 2.1095 | Valid Acc: 0.6942
Validation loss improved from 2.1129 to 2.1095. 체크포인트를 저장합니다.


In [29]:
model.load_state_dict(torch.load('best_model_checkpoint.pth', weights_only=True))
model.to(device)

val_loss, val_accuracy = evaluation(model, valid_dataloader, loss_function, device)

print(f'Best model validation loss: {val_loss:.4f}')
print(f'Best model validation accuracy: {val_accuracy:.4f}')

Best model validation loss: 2.1102
Best model validation accuracy: 0.6925


In [30]:
def seq_to_src(input_seq):
  sentence = ''
  for encoded_word in input_seq:
    if(encoded_word != 0):
      sentence = sentence + index2src[encoded_word] + ' '
  return sentence

def seq_to_tar(input_seq):
  sentence = ''
  for encoded_word in input_seq:
    if(encoded_word != 0 and encoded_word != tgt_vocab['<sos>'] and encoded_word != tgt_vocab['<eos>']):
      sentence = sentence + index2tar[encoded_word] + ' '
  return sentence

In [31]:
def decode_sequence(input_seq, model):
    model.eval()
    encoder_inputs = torch.LongTensor(input_seq).unsqueeze(0).to(device)
    src_mask = model.make_src_mask(encoder_inputs)
    encoder_out = model.encode(encoder_inputs, src_mask)

    decoded_tokens = [tgt_vocab['<sos>']]

    with torch.no_grad():
        for _ in range(max_len):
            decoder_input = torch.LongTensor(decoded_tokens).unsqueeze(0).to(device)
            tgt_mask = model.make_tgt_mask(decoder_input)
            src_tgt_mask = model.make_src_tgt_mask(encoder_inputs, decoder_input)
            output = model.decode(decoder_input, encoder_out, tgt_mask, src_tgt_mask)
            output = model.generator(output)

            output_token = output.argmax(dim=2)[:, -1].item()

            if output_token == tgt_vocab['<eos>']:
                break

            decoded_tokens.append(output_token)

    return ' '.join(index2tar[token] for token in decoded_tokens if token != tgt_vocab['<sos>'])


In [32]:
for seq_index in [3, 50, 100, 300, 1001]:
    input_seq = encoder_input_train[seq_index]
    translated_text = decode_sequence(input_seq, model)

    print("입력문장: ", seq_to_src(encoder_input_train[seq_index]))
    print("정답문장: ", seq_to_tar(decoder_input_train[seq_index]))
    print("번역문장: ", translated_text)
    print("-"*50)

입력문장:  where s the beach ? 
정답문장:  ou est la plage ? 
번역문장:  ou sont les cheveux ?
--------------------------------------------------
입력문장:  tom won t retire . 
정답문장:  tom ne prendra pas sa retraite . 
번역문장:  tom ne prendra pas en francais .
--------------------------------------------------
입력문장:  tom is my nephew . 
정답문장:  tom est mon neveu . 
번역문장:  tom est mon neveu .
--------------------------------------------------
입력문장:  be confident . 
정답문장:  sois confiant ! 
번역문장:  soyez confiants !
--------------------------------------------------
입력문장:  don t tell anybody . 
정답문장:  ne le dis a quiconque ! 
번역문장:  ne le dis a personne !
--------------------------------------------------
